### PR TITLE
Prefer intercom access token to  appId/apiKey

### PR DESCRIPTION
**Pull request by gcoombe**
As noted in #56  As of January 2017 Intercom has deprecated apiKeys and accessKey's must be used (https://developers.intercom.com/docs/personal-access-tokens).  This pull request adds support for using accessTokens but retains support apiKey/appId with a deprecation notice.

I haven't been able to test this end to end with a apiKey/appId since the intercom interface no longer allows you to create one.

Another important note is that the intercom api now requires an "extended" access token to read conversations.  To obtain one of these tokens you must submit a request for the intercom team to review.

### CODE REVIEW

**Comment by arnaudbesnier** [comment]
@gcoombe Thanks for the contribution! We'll look into your code soon.

**Comment by gcoombe** [comment]
Any feedback on this?  I'd like to get off using my fork once this can get resolved.  The intercom integration is a must have for me.

**Comment by arnaudbesnier** [comment]
@gcoombe my bad, I have to do my homework 😅.
I'll validate your code this week.

**Comment by arnaudbesnier** [comment]
Hey @gcoombe I made a new PR https://github.com/ForestAdmin/forest-express/pull/75 based on your code. I tested it and it seems ok. Can you review the code and test it?

Thanks for the contribution!

**Comment by arnaudbesnier** [comment]
I close this PR as we are almost ready to validate this new one: https://github.com/ForestAdmin/forest-express/pull/75

**Pull request closed without merging**
