### PR TITLE
modify attributes on virtual field update

### PR DESCRIPTION
**Pull request by vquesnel**
When updating virtual field modify only attributes[field.field] and not set attributes to this virtual field data

### CODE REVIEW

**Comment by arnaudbesnier** [comment]
Hi @vquesnel, thanks for the contribution.

I don't really understand the issue.
If you define a Smart Field `set` method, this method is supposed to return the record object once done (see the documentation http://doc.forestadmin.com/developers-guide/#updating-a-smart-field).

Can you explain your use case or send the implementation of your Smart Field `set` method? It would help a lot. 

🌲🌲🌲

**Comment by vquesnel** [comment]
`Liana.collection('OrderItem', {
  fields: [{
    field: '_unitPrice',
    type: 'Number',
    get(item) {
      return item.unitPrice / 100;
    },
    set(item, value) {
      return item.unitPrice = Math.round(value * 100);
    },
  }],
});
`
This is my smart field to calculate the unit price for each item, but when I try to update an item I've got an error telling me that it can't creat property "updatedAt' on number <XXXX> because:

`attributes = field.set(attributes, attributes[field.field]);
  return attributes;`
do not return an object but a value, on the other hand 

`attributes[field.field] = field.set(attributes, attributes[field.field]);
  return attributes;`
return the attributes object with the updated field.

**Comment by arnaudbesnier** [comment]
@vquesnel ,

As you can see in the doc, you have to set your Smart Field this way:
```
Liana.collection('OrderItem', {
  fields: [{
    field: '_unitPrice',
    type: 'Number',
    get(item) { return item.unitPrice / 100; },
    set(item, value) {
      item.unitPrice = Math.round(value * 100);
      // NOTICE: You must return the record here. 
      return item;
    }
  }]
});
```

**Comment by vquesnel** [comment]
Oops, my bad i read a bit to fast your doc 😣
Sorry!

**Comment by vquesnel** [comment]
All work perfectly with this modification! 👍

**Pull request closed without merging**
